# default question formatting
default:
  confirmation: Do you want to enable {friendly_name} ({friendly_description})?
  file_path: What is the path for {friendly_name} ({friendly_description})?
  email: Which user/group email should be responsible for {friendly_name} ({friendly_description})?
  text: What should the value be for {friendly_name} ({friendly_description})?

questions:
  - config_variable: application_admin
    friendly_name: Adminstration of ConsoleMe
    friendly_description: Enter your team's e-mail address here. This e-mail will be used as the default approvers of IAM policy requests
    type: email
  - config_variable: tornado.debug
    friendly_name: Tornado Debug mode
    friendly_description: "Warning: if running in production, don't set debug on!"
    type: confirmation
    default: False
  - config_variable: tornado.port
    friendly_name: Tornado Port
    friendly_description: the port to run tornado on
    type: text
    default: "8081"
  - config_variable: tornado.xsrf
    friendly_name: Tornado XSRF
    friendly_description: whether to turn on XSRF protection or not
    type: confirmation
    default: True
