version: '3'
# Never use this in a production environment.
# Run with docker-compose -f docker-compose-saml.yaml up
services:
  consoleme:
    build: .
    ports:
      - "8081:8081"
    tty: true
    stdin_open: true
    volumes:
      - .:/apps/consoleme
      - ~/.aws:/root/.aws
      - ~/.ssh:/root/.ssh
    environment:
      - CONFIG_LOCATION=/apps/consoleme/docker/example_config_saml.yaml
    # Run commands to install Consoleme, run the service, and never exit in the event of failure (For dev debugging)
    command: >
      bash -c 'pip install argh watchdog; pip install -e /apps/consoleme/default_plugins;
      watchmedo auto-restart --recursive --pattern="*.py;*.yaml" --directory="." python consoleme/__main__.py'
    depends_on:
      - consoleme_redis
      - consoleme_dynamodb
    links:
      - consoleme_redis
      - consoleme_dynamodb

  consoleme_saml:
    image: "kristophjunge/test-saml-idp"
    volumes:
      - ./docker/simplesamlphp/authsources.php:/var/www/simplesamlphp/config/authsources.php
    container_name: consoleme_simplesaml
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=http://127.0.0.1:8081
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://127.0.0.1:8081/saml/acs
  consoleme_redis:
    container_name: consoleme_redis
    image: "redis:alpine"

  consoleme_dynamodb:
    image: "cnadiminti/dynamodb-local"
    container_name: consoleme_dynamodb
    entrypoint: java
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data -port 8005"
    restart: always
    volumes:
      - ./dynamodb-data:/data