version: '3'
# Never use this in a production environment.
# Run with docker-compose -f docker-compose-test.yaml up
services:
  python-tests:
    build: .
    environment:
      - CONFIG_LOCATION=/apps/consoleme/docker/example_config_test.yaml
    volumes:
      - .:/apps/consoleme
      - ~/.aws:/root/.aws
      - ~/.ssh:/root/.ssh
    # entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." pytest
    entrypoint: >
      bash -c 'pip install argh watchdog; pip install -e /apps/consoleme/default_plugins;
      watchmedo auto-restart --recursive --pattern="*.py;*.yaml" --directory="." make test'

  consoleme_redis:
    container_name: consoleme_redis
    image: "redis:alpine"

  consoleme_dynamodb:
    image: "cnadiminti/dynamodb-local"
    container_name: consoleme_dynamodb
    entrypoint: java
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data -port 8005"
    restart: always
    volumes:
      - ./dynamodb-data:/data



