version: '3'
# Never use this in a production environment.
services:
  consoleme:
    build: .
    ports:
      - "8081:8081"
    tty: true
    stdin_open: true
    volumes:
      - .:/apps/consoleme
      - ~/.aws:/root/.aws
      - ~/.ssh:/root/.ssh
    environment:
      - CONFIG_LOCATION=/apps/consoleme/docker/example_config_test.yaml
    # Run commands to install Consoleme, run the service, and never exit in the event of failure (For dev debugging)
    command: >
      bash -c 'pip install argh watchdog; pip install -e /apps/consoleme/default_plugins;
      watchmedo auto-restart --recursive --pattern="*.py;*.yaml" --directory="." python consoleme/__main__.py'
    depends_on:
      - consoleme_redis
      - consoleme_dynamodb
    links:
      - consoleme_redis
      - consoleme_dynamodb

  consoleme_redis:
    container_name: consoleme_redis
    ports:
      - "6379:6379"
    image: "redis:alpine"

  consoleme_dynamodb:
    image: "cnadiminti/dynamodb-local"
    container_name: consoleme_dynamodb
    entrypoint: java
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data -port 8005"
    ports:
      - "8005:8005"
    restart: always
    volumes:
      - ./dynamodb-data:/data

