name: pre-commit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libssl-dev libcurl4-openssl-dev python3-dev build-essential libxml2-dev libxmlsec1-dev libxmlsec1-openssl musl-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        pip install -r requirements-docs.txt
        pip install -e .
        pip install -e default_plugins
        pre-commit install
    - name: Run pre-commit
      run: |
        pre-commit run -a
